import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-teal-500 py-5">
          <Link className="px-5" href={"/"}>
            Home
          </Link>
          <Link className="px-5" href={"/charities"}>
            Charities
          </Link>
          <Link className="px-5" href={"/signup"}>
            SignUp
          </Link>
          <Link className="px-5" href={"/signin"}>
            Signin
          </Link>
          <Link className="px-5" href={"/account"}>
            Account
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
